"""Sample data saham IDX (40 emiten LQ45 + populer).
Mirror dari src/lib/expertSystem.ts SAMPLE_STOCKS.
"""

SAMPLE_STOCKS = [
    {"ticker": "BBCA", "name": "Bank Central Asia",          "sector": "Perbankan",       "price": 9850,  "per": 22.4, "pbv": 4.6,  "roe": 21.5,  "der": 0.18, "dividend_yield": 2.4,  "eps": 440,  "net_profit_growth": 12.4,  "rsi": 58, "macd_signal": "bullish", "ma50_trend": "up",       "volume_strength": "high",   "market_cap": 1215, "beta": 0.85},
    {"ticker": "BBRI", "name": "Bank Rakyat Indonesia",      "sector": "Perbankan",       "price": 4720,  "per": 12.1, "pbv": 2.3,  "roe": 19.8,  "der": 0.22, "dividend_yield": 6.1,  "eps": 390,  "net_profit_growth": 8.2,   "rsi": 52, "macd_signal": "neutral", "ma50_trend": "sideways", "volume_strength": "high",   "market_cap": 715,  "beta": 1.05},
    {"ticker": "BMRI", "name": "Bank Mandiri",               "sector": "Perbankan",       "price": 6300,  "per": 11.5, "pbv": 2.1,  "roe": 18.4,  "der": 0.24, "dividend_yield": 5.4,  "eps": 548,  "net_profit_growth": 14.1,  "rsi": 61, "macd_signal": "bullish", "ma50_trend": "up",       "volume_strength": "high",   "market_cap": 588,  "beta": 1.10},
    {"ticker": "BBNI", "name": "Bank Negara Indonesia",      "sector": "Perbankan",       "price": 4580,  "per": 9.2,  "pbv": 1.3,  "roe": 15.2,  "der": 0.31, "dividend_yield": 6.8,  "eps": 498,  "net_profit_growth": 10.8,  "rsi": 47, "macd_signal": "neutral", "ma50_trend": "sideways", "volume_strength": "normal", "market_cap": 171,  "beta": 1.20},
    {"ticker": "BRIS", "name": "Bank Syariah Indonesia",     "sector": "Perbankan",       "price": 2680,  "per": 18.6, "pbv": 2.8,  "roe": 16.4,  "der": 0.28, "dividend_yield": 1.8,  "eps": 144,  "net_profit_growth": 22.5,  "rsi": 64, "macd_signal": "bullish", "ma50_trend": "up",       "volume_strength": "normal", "market_cap": 124,  "beta": 1.15},
    {"ticker": "BBTN", "name": "Bank Tabungan Negara",       "sector": "Perbankan",       "price": 1265,  "per": 6.8,  "pbv": 0.6,  "roe": 9.2,   "der": 0.85, "dividend_yield": 3.2,  "eps": 186,  "net_profit_growth": -4.5,  "rsi": 36, "macd_signal": "bearish", "ma50_trend": "down",     "volume_strength": "low",    "market_cap": 18,   "beta": 1.35},
    {"ticker": "TLKM", "name": "Telkom Indonesia",           "sector": "Telekomunikasi",  "price": 2780,  "per": 13.8, "pbv": 2.4,  "roe": 16.2,  "der": 0.65, "dividend_yield": 5.8,  "eps": 201,  "net_profit_growth": -2.1,  "rsi": 38, "macd_signal": "bearish", "ma50_trend": "down",     "volume_strength": "high",   "market_cap": 275,  "beta": 0.95},
    {"ticker": "ISAT", "name": "Indosat Ooredoo Hutchison",  "sector": "Telekomunikasi",  "price": 2450,  "per": 14.5, "pbv": 2.2,  "roe": 15.8,  "der": 1.45, "dividend_yield": 3.4,  "eps": 169,  "net_profit_growth": 28.6,  "rsi": 56, "macd_signal": "bullish", "ma50_trend": "up",       "volume_strength": "normal", "market_cap": 80,   "beta": 1.10},
    {"ticker": "EXCL", "name": "XL Axiata",                  "sector": "Telekomunikasi",  "price": 2150,  "per": 19.2, "pbv": 1.1,  "roe": 5.8,   "der": 1.62, "dividend_yield": 2.1,  "eps": 112,  "net_profit_growth": 6.4,   "rsi": 49, "macd_signal": "neutral", "ma50_trend": "sideways", "volume_strength": "normal", "market_cap": 28,   "beta": 1.05},
    {"ticker": "UNVR", "name": "Unilever Indonesia",         "sector": "Konsumen",        "price": 2240,  "per": 25.6, "pbv": 18.2, "roe": 71.2,  "der": 1.85, "dividend_yield": 4.1,  "eps": 87,   "net_profit_growth": -8.5,  "rsi": 32, "macd_signal": "bearish", "ma50_trend": "down",     "volume_strength": "normal", "market_cap": 85,   "beta": 0.65},
    {"ticker": "ICBP", "name": "Indofood CBP",               "sector": "Konsumen",        "price": 11250, "per": 16.8, "pbv": 3.2,  "roe": 19.4,  "der": 0.92, "dividend_yield": 2.8,  "eps": 670,  "net_profit_growth": 11.5,  "rsi": 55, "macd_signal": "bullish", "ma50_trend": "up",       "volume_strength": "normal", "market_cap": 131,  "beta": 0.75},
    {"ticker": "INDF", "name": "Indofood Sukses Makmur",     "sector": "Konsumen",        "price": 6750,  "per": 7.4,  "pbv": 1.0,  "roe": 14.2,  "der": 0.74, "dividend_yield": 4.6,  "eps": 912,  "net_profit_growth": 8.8,   "rsi": 53, "macd_signal": "bullish", "ma50_trend": "up",       "volume_strength": "normal", "market_cap": 59,   "beta": 0.85},
    {"ticker": "GGRM", "name": "Gudang Garam",               "sector": "Konsumen",        "price": 16800, "per": 14.2, "pbv": 0.8,  "roe": 5.8,   "der": 0.42, "dividend_yield": 5.2,  "eps": 1183, "net_profit_growth": -12.4, "rsi": 41, "macd_signal": "neutral", "ma50_trend": "sideways", "volume_strength": "low",    "market_cap": 32,   "beta": 0.70},
    {"ticker": "HMSP", "name": "HM Sampoerna",               "sector": "Konsumen",        "price": 765,   "per": 11.2, "pbv": 3.4,  "roe": 30.5,  "der": 0.18, "dividend_yield": 8.4,  "eps": 68,   "net_profit_growth": -5.2,  "rsi": 42, "macd_signal": "neutral", "ma50_trend": "sideways", "volume_strength": "normal", "market_cap": 89,   "beta": 0.60},
    {"ticker": "MYOR", "name": "Mayora Indah",               "sector": "Konsumen",        "price": 2540,  "per": 17.4, "pbv": 3.1,  "roe": 18.6,  "der": 0.48, "dividend_yield": 1.4,  "eps": 146,  "net_profit_growth": 16.8,  "rsi": 60, "macd_signal": "bullish", "ma50_trend": "up",       "volume_strength": "normal", "market_cap": 57,   "beta": 0.95},
    {"ticker": "JPFA", "name": "Japfa Comfeed",              "sector": "Konsumen",        "price": 1640,  "per": 8.6,  "pbv": 1.2,  "roe": 14.8,  "der": 0.92, "dividend_yield": 4.8,  "eps": 191,  "net_profit_growth": 24.5,  "rsi": 62, "macd_signal": "bullish", "ma50_trend": "up",       "volume_strength": "normal", "market_cap": 19,   "beta": 1.10},
    {"ticker": "ANTM", "name": "Aneka Tambang",              "sector": "Pertambangan",    "price": 1565,  "per": 11.4, "pbv": 1.6,  "roe": 14.8,  "der": 0.36, "dividend_yield": 3.4,  "eps": 137,  "net_profit_growth": 18.6,  "rsi": 67, "macd_signal": "bullish", "ma50_trend": "up",       "volume_strength": "high",   "market_cap": 38,   "beta": 1.45},
    {"ticker": "PTBA", "name": "Bukit Asam",                 "sector": "Pertambangan",    "price": 2680,  "per": 4.8,  "pbv": 1.4,  "roe": 30.2,  "der": 0.15, "dividend_yield": 12.5, "eps": 558,  "net_profit_growth": -22.4, "rsi": 48, "macd_signal": "neutral", "ma50_trend": "sideways", "volume_strength": "normal", "market_cap": 31,   "beta": 1.25},
    {"ticker": "ADRO", "name": "Adaro Energy",               "sector": "Pertambangan",    "price": 2580,  "per": 4.2,  "pbv": 1.1,  "roe": 26.8,  "der": 0.42, "dividend_yield": 11.2, "eps": 614,  "net_profit_growth": -30.5, "rsi": 44, "macd_signal": "bearish", "ma50_trend": "down",     "volume_strength": "high",   "market_cap": 82,   "beta": 1.40},
    {"ticker": "ITMG", "name": "Indo Tambangraya Megah",     "sector": "Pertambangan",    "price": 26500, "per": 3.8,  "pbv": 1.2,  "roe": 32.5,  "der": 0.12, "dividend_yield": 18.4, "eps": 6974, "net_profit_growth": -28.2, "rsi": 46, "macd_signal": "neutral", "ma50_trend": "sideways", "volume_strength": "normal", "market_cap": 30,   "beta": 1.30},
    {"ticker": "MDKA", "name": "Merdeka Copper Gold",        "sector": "Pertambangan",    "price": 2380,  "per": 32.4, "pbv": 4.2,  "roe": 13.8,  "der": 1.25, "dividend_yield": 0,    "eps": 73,   "net_profit_growth": 42.5,  "rsi": 71, "macd_signal": "bullish", "ma50_trend": "up",       "volume_strength": "high",   "market_cap": 58,   "beta": 1.55},
    {"ticker": "INCO", "name": "Vale Indonesia",             "sector": "Pertambangan",    "price": 3420,  "per": 18.6, "pbv": 1.5,  "roe": 8.2,   "der": 0.18, "dividend_yield": 2.4,  "eps": 184,  "net_profit_growth": -45.6, "rsi": 35, "macd_signal": "bearish", "ma50_trend": "down",     "volume_strength": "normal", "market_cap": 34,   "beta": 1.50},
    {"ticker": "MEDC", "name": "Medco Energi",               "sector": "Energi",          "price": 1185,  "per": 6.4,  "pbv": 1.0,  "roe": 16.4,  "der": 1.85, "dividend_yield": 3.2,  "eps": 185,  "net_profit_growth": -18.4, "rsi": 41, "macd_signal": "neutral", "ma50_trend": "sideways", "volume_strength": "normal", "market_cap": 30,   "beta": 1.40},
    {"ticker": "PGAS", "name": "Perusahaan Gas Negara",      "sector": "Energi",          "price": 1605,  "per": 8.4,  "pbv": 0.9,  "roe": 11.2,  "der": 0.82, "dividend_yield": 7.4,  "eps": 191,  "net_profit_growth": 5.6,   "rsi": 51, "macd_signal": "bullish", "ma50_trend": "up",       "volume_strength": "normal", "market_cap": 39,   "beta": 1.05},
    {"ticker": "ASII", "name": "Astra International",        "sector": "Aneka Industri",  "price": 5025,  "per": 8.2,  "pbv": 1.1,  "roe": 14.5,  "der": 0.78, "dividend_yield": 7.2,  "eps": 613,  "net_profit_growth": -4.2,  "rsi": 44, "macd_signal": "neutral", "ma50_trend": "sideways", "volume_strength": "high",   "market_cap": 203,  "beta": 1.05},
    {"ticker": "UNTR", "name": "United Tractors",            "sector": "Aneka Industri",  "price": 26800, "per": 5.4,  "pbv": 1.2,  "roe": 23.4,  "der": 0.32, "dividend_yield": 12.8, "eps": 4963, "net_profit_growth": -16.8, "rsi": 50, "macd_signal": "neutral", "ma50_trend": "sideways", "volume_strength": "normal", "market_cap": 100,  "beta": 1.20},
    {"ticker": "BSDE", "name": "Bumi Serpong Damai",         "sector": "Properti",        "price": 1085,  "per": 7.2,  "pbv": 0.6,  "roe": 8.4,   "der": 0.52, "dividend_yield": 1.8,  "eps": 151,  "net_profit_growth": 12.4,  "rsi": 54, "macd_signal": "bullish", "ma50_trend": "up",       "volume_strength": "normal", "market_cap": 23,   "beta": 1.25},
    {"ticker": "PWON", "name": "Pakuwon Jati",               "sector": "Properti",        "price": 408,   "per": 8.6,  "pbv": 1.0,  "roe": 12.5,  "der": 0.38, "dividend_yield": 2.6,  "eps": 47,   "net_profit_growth": 8.2,   "rsi": 49, "macd_signal": "neutral", "ma50_trend": "sideways", "volume_strength": "normal", "market_cap": 20,   "beta": 1.30},
    {"ticker": "CTRA", "name": "Ciputra Development",        "sector": "Properti",        "price": 1130,  "per": 11.4, "pbv": 1.0,  "roe": 9.5,   "der": 0.62, "dividend_yield": 1.5,  "eps": 99,   "net_profit_growth": 4.2,   "rsi": 46, "macd_signal": "neutral", "ma50_trend": "sideways", "volume_strength": "low",    "market_cap": 21,   "beta": 1.20},
    {"ticker": "WIKA", "name": "Wijaya Karya",               "sector": "Konstruksi",      "price": 312,   "per": 0,    "pbv": 0.4,  "roe": -18.5, "der": 3.85, "dividend_yield": 0,    "eps": -185, "net_profit_growth": -120.5, "rsi": 28,"macd_signal": "bearish", "ma50_trend": "down",     "volume_strength": "low",    "market_cap": 3,    "beta": 1.65},
    {"ticker": "PTPP", "name": "PP (Persero)",               "sector": "Konstruksi",      "price": 384,   "per": 14.8, "pbv": 0.3,  "roe": 2.1,   "der": 2.45, "dividend_yield": 0,    "eps": 26,   "net_profit_growth": -35.4, "rsi": 32, "macd_signal": "bearish", "ma50_trend": "down",     "volume_strength": "low",    "market_cap": 2,    "beta": 1.55},
    {"ticker": "KLBF", "name": "Kalbe Farma",                "sector": "Kesehatan",       "price": 1620,  "per": 22.1, "pbv": 3.5,  "roe": 16.8,  "der": 0.21, "dividend_yield": 2.2,  "eps": 73,   "net_profit_growth": 6.4,   "rsi": 46, "macd_signal": "neutral", "ma50_trend": "sideways", "volume_strength": "normal", "market_cap": 76,   "beta": 0.80},
    {"ticker": "MIKA", "name": "Mitra Keluarga Karyasehat",  "sector": "Kesehatan",       "price": 2780,  "per": 28.6, "pbv": 5.4,  "roe": 19.8,  "der": 0.05, "dividend_yield": 2.4,  "eps": 97,   "net_profit_growth": 14.5,  "rsi": 58, "macd_signal": "bullish", "ma50_trend": "up",       "volume_strength": "normal", "market_cap": 41,   "beta": 0.70},
    {"ticker": "GOTO", "name": "GoTo Gojek Tokopedia",       "sector": "Teknologi",       "price": 65,    "per": 0,    "pbv": 1.4,  "roe": -22.5, "der": 0.18, "dividend_yield": 0,    "eps": -22,  "net_profit_growth": 35.4,  "rsi": 38, "macd_signal": "bearish", "ma50_trend": "down",     "volume_strength": "high",   "market_cap": 78,   "beta": 1.85},
    {"ticker": "BUKA", "name": "Bukalapak",                  "sector": "Teknologi",       "price": 118,   "per": 0,    "pbv": 0.5,  "roe": -8.4,  "der": 0.12, "dividend_yield": 0,    "eps": -12,  "net_profit_growth": 58.2,  "rsi": 42, "macd_signal": "neutral", "ma50_trend": "sideways", "volume_strength": "normal", "market_cap": 12,   "beta": 1.70},
    {"ticker": "EMTK", "name": "Elang Mahkota Teknologi",    "sector": "Teknologi",       "price": 545,   "per": 18.4, "pbv": 0.8,  "roe": 4.2,   "der": 0.28, "dividend_yield": 1.2,  "eps": 30,   "net_profit_growth": -12.4, "rsi": 40, "macd_signal": "bearish", "ma50_trend": "down",     "volume_strength": "low",    "market_cap": 32,   "beta": 1.35},
    {"ticker": "JSMR", "name": "Jasa Marga",                 "sector": "Infrastruktur",   "price": 4920,  "per": 9.4,  "pbv": 1.1,  "roe": 12.4,  "der": 1.85, "dividend_yield": 3.8,  "eps": 523,  "net_profit_growth": 18.5,  "rsi": 56, "macd_signal": "bullish", "ma50_trend": "up",       "volume_strength": "normal", "market_cap": 36,   "beta": 1.10},
    {"ticker": "SMGR", "name": "Semen Indonesia",            "sector": "Industri Dasar",  "price": 3650,  "per": 13.6, "pbv": 0.7,  "roe": 5.4,   "der": 0.62, "dividend_yield": 4.5,  "eps": 268,  "net_profit_growth": -22.4, "rsi": 39, "macd_signal": "bearish", "ma50_trend": "down",     "volume_strength": "normal", "market_cap": 24,   "beta": 1.15},
    {"ticker": "INTP", "name": "Indocement Tunggal Prakarsa","sector": "Industri Dasar",  "price": 6800,  "per": 14.2, "pbv": 1.4,  "roe": 9.8,   "der": 0.18, "dividend_yield": 4.2,  "eps": 479,  "net_profit_growth": -8.4,  "rsi": 43, "macd_signal": "neutral", "ma50_trend": "sideways", "volume_strength": "normal", "market_cap": 25,   "beta": 1.05},
    {"ticker": "SIDO", "name": "Sido Muncul",                "sector": "Kesehatan",       "price": 615,   "per": 14.8, "pbv": 5.6,  "roe": 38.4,  "der": 0.04, "dividend_yield": 6.8,  "eps": 42,   "net_profit_growth": 11.2,  "rsi": 54, "macd_signal": "bullish", "ma50_trend": "up",       "volume_strength": "normal", "market_cap": 18,   "beta": 0.65},
    {"ticker": "AKRA", "name": "AKR Corporindo",             "sector": "Energi",          "price": 1485,  "per": 11.2, "pbv": 2.4,  "roe": 21.8,  "der": 0.22, "dividend_yield": 5.4,  "eps": 132,  "net_profit_growth": 14.6,  "rsi": 57, "macd_signal": "bullish", "ma50_trend": "up",       "volume_strength": "normal", "market_cap": 30,   "beta": 0.95},
]


def get_stock(ticker: str):
    for s in SAMPLE_STOCKS:
        if s["ticker"].upper() == ticker.upper():
            return s
    return None


import math, random

def generate_price_history(ticker: str, days: int = 60):
    """Generate price history (deterministic per ticker) untuk feed ke modul C++."""
    stock = get_stock(ticker)
    if not stock:
        return []
    seed = sum(ord(c) for c in ticker)
    rng = random.Random(seed)
    base = stock["price"]
    p = base * 0.92
    prices = []
    for i in range(days):
        change = rng.uniform(-0.025, 0.028) + math.sin(i / 8) * 0.005
        p = max(1, p * (1 + change))
        prices.append(round(p, 2))
    prices[-1] = base
    return prices
